'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var multer = require("multer");
var upload = multer({ dest: 'public/upload/' });
var controller = require("./upload.controller");
var auth = require("../../auth/auth.service");
var router = express.Router();
router.post('/upload/singleimg', auth.isAuthenticated(), upload.single('file'), controller.uploadFile);
router.post('/upload/:collection/:id', auth.isAuthenticated(), upload.single('file'), controller.uploadimage);
router.post('/remove/:filename', auth.isAuthenticated(), controller.removeFile);
router.get('/get/:filename', controller.image);
module.exports = router;
